Translations = {
    ["BR"] = {
	    ["994732206"] = {
			-- Others --
			["Social Media"] = "Redes Sociais",
			["Farm"] = "Farmar",
			["Quests/Items"] = "Missões/Itens",
			["Sea Events"] = "Eventos Marítimos",
			["Islands"] = "Ilhas",
			["Fruits/Raid"] = "Frutas/Raid",
			["Teleport"] = "Teletransporte",
			["Stats"] = "Estatísticas",
			["Player"] = "Jogador",
			["Race"] = "Raça",
			["Shop"] = "Loja",
			["Visual"] = "Visual",
			["Misc"] = "Miscelânea",
			-- Social --
			["Someone Hub | Community"] = "Someone Hub | Comunidade",
			["Join The Best Roblox Scripting Community"] = "Junte-Se A Melhor Comunidade De Scripts Do Roblox",
			["Someone Hub Official Channel"] = "Someone Hub Canal Oficial",
			["Sign Up To Receive Updates About The Script As Soon As Possible."] = "Se Inscreva Para Receber Novidades Sobre O Script O Mais Rápido Possível",
			-- Misc --
			["Settings"] = "Configurações",
				["Select Weapon"] = "Selecione Arma",
				["Select The Weapon That Will Be Used For General Farming"] = "Selecione A Arma Que Será Usada Para O Farm Geral",
				["Tween Speed"] = "Velocidade Da Speed",
				["Bring Enemies"] = "Trazer Inimigos",
				["Brings Enemies Close To Make Farming Easier"] = "Trás Inimigos Para Perto Para Facilitar O Farm",
				["Auto Buso Haki"] = "Auto Buso Haki",
				["Activates Buso Haki Whenever It Deactivates"] = "Ativa Buso Haki Sempre Que Ele Desativar",
				["Auto Attack"] = "Auto Atacar",
				["Attacks Nearby Players And Enemies"] = "Ataca Jogadores E Inimigos Próximos",
				["Activate V3"] = "Ativar V3",
				["Activates Race Ability V3 When Possible"] = "Ativa A Habilidade V3 Da Raça Quando Possível",
				["Enable V4"] = "Ativar V4",
				["Activates Race V4 Transformation When Charged"] = "Ativa A Transformação V4 Da Raça Quando Possível",
			["Codes"] = "Códigos",
				["Redeem Codes to Get Rewards"] = "Resgata Códigos Para Conseguir Recompensas",
			["Menus"] = "Menus",
			["Team"] = "Time",
			["More FPS"] = "Mais FPS",
			["Others"] = "Outros",
			-- Farm --
			["Chest"] = "Baú",
			["Ectoplasm"] = "Ectoplasma",
			["Bones"] = "Ossos",
			["Eagle Boss"] = "Chefe Água",
			["Elite Hunters"] = "Caçadores De Elite",
			["Bosses"] = "Chefes",
			["Mastery"] = "Maestria",
			-- Quests --
			["Second Sea"] = "Segundo Mar",
			["Third Sea"] = "Terceiro Mar",
			["Don Swan"] = "Don Swan",
			["Bartilo Quest"] = "Missão Do Bartilo",
			["Citizen Quest"] = "Missão Do Cidadão",
			["Law Boss"] = "Chefe Law",
			["Barista Cousin"] = "Primo Do Barista",
			["Berries"] = "Bagas",
			-- Sea Events --
			["Settings"] = "Configurações",
			-- Islands --
			["Kitsune Island"] = "Ilha Da Kitsune",
			["Mirage Island"] = "Ilha Da Miragem",
			["Prehistoric Island"] = "Ilha Pre-Historica",
			["Frozen Dimension"] = "Dimensão Congelada",
			-- Fruits --
			["Fruits"] = "Frutas",
			-- Teleport --
			["Seas"] = "Mares",
			-- Stats --
			-- Player --
			["Local Player"] = "Seu Personagem",
			["Aimbot Nearest"] = "Aimbot No Mais Próximo",
			["Target The Nearest Player"] = "Mira No Jogador Mais Próximo",
			-- Race --
			["To Evolve"] = "Evoluir",
			["Unlock Races"] = "Desbloquear Race",
			-- Shop --
			["Christmas"] = "Natal",
			["Valentine's Day"] = "Dia Dos Namorados",
			["Ectoplasm"] = "Ectoplasma",
			["Misc"] = "Miscelânea",
			["Fighting Styles"] = "Estilos De Luta",
			["Swords"] = "Espadas",
			["Guns"] = "Armas De Fogo",
			["Accessories"] = "Acessórios",
			["Races"] = "Raças",
			["Volcano Event"] = "Evento Do Vulcão",
			["Beast Hunter"] = "Caçador De Feras",
			["Shark Hunter"] = "Caçador De Tubarões",
			["Dragon Talon Sage"] = "Sábio Garra De Dragão",
			-- Visual --
			["Extra Sensory Perception"] = "Percepção Extra Sensorial",
			["Font Size"] = "Tamanho Da Fonte",
			["Font Size To Be Used"] = "Tamanho Da Fonte Que Será Usada",
			["Select Font"] = "Selecione A Fonte",
			["Choose The Font That Will Be Used In The ESPs"] = "Escolha A Fonte Que Será Usada Nos ESPs",
			["ESP Players"] = "ESP Jogadores",
			["See Name, Distance, Health And Energy"] = "Veja Nome, Distância, Saúde E Energia",
			["ESP Fruits"] = "ESP Frutas",
			["See Name And Distance"] = "Veja Nome E Distância",
			["ESP Berries"] = "ESP Bagas",
			["ESP Chests"] = "ESP Baús",
			["ESP Islands"] = "ESP Ilhas",
			["ESP Flowers"] = "ESP Flores",
		},
	},
    ["TH"] = {
		[""] = {
		},
	},
    ["VN"] = {
		[""] = {
		},
	},
}